name: Create Release and Update Repository

on:
  workflow_call:
    inputs:
      internal_name:
        type: string
        required: true
      solution_name:
        type: string
        required: true
      module_name:
        type: string
        required: true
      build_configuration:
        type: string
        required: true
      personal_plugin_repo:
        type: string
        required: true
      personal_plugin_repo_branch:
        type: string
        required: true
    secrets:
      PAT:
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.solution_name }}.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: msbuild ${{ inputs.solution_name }}.sln /p:Configuration=${{ inputs.build_configuration }}

      - name: Get Changelog
        run: |
          New-Variable -Name "CHANGELOG" -Visibility Public -Value $(git tag -l ${{ github.ref_name }} --format='%(contents:body)')
          echo "CHANGELOG=$CHANGELOG" >> $env:GITHUB_ENV
          echo "Changelog set to: $CHANGELOG"

      - name: Attach Changelog 1
        uses: richardrigutins/replace-in-files@v2
        with:
          files: ./${{ inputs.module_name }}/bin/x64/${{ inputs.build_configuration }}/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json
          search-text: '"Changelog": ""'
          replacement-text: '"Changelog": "${{ env.CHANGELOG }}"'

      - name: Attach Changelog 2
        uses: richardrigutins/replace-in-files@v2
        with:
          files: ./${{ inputs.module_name }}/bin/x64/${{ inputs.build_configuration }}/${{ inputs.internal_name }}.json
          search-text: '"Changelog": ""'
          replacement-text: '"Changelog": "${{ env.CHANGELOG }}"'

      - name: Check JSON
        run: cat ./${{ inputs.module_name }}/bin/x64/${{ inputs.build_configuration }}/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./${{ inputs.module_name }}/bin/x64/${{ inputs.build_configuration }}/*

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.personal_plugin_repo }}
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.personal_plugin_repo_branch }}

      - name: Download Plugin Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: plugins/${{ inputs.internal_name }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: ${{ inputs.internal_name }} ${{ github.ref_name }}

      - name: Get Changelog
        run: |
          cat ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json
          New-Variable -Name "CHANGELOG" -Visibility Public -Value $((Get-Content ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json | ConvertFrom-Json).Changelog)
          echo "CHANGELOG=$CHANGELOG" >> $env:GITHUB_ENV
          echo "Found changelog: $CHANGELOG"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.CHANGELOG }}
          files: ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}/latest.zip
          draft: false
          prerelease: false